project:
  type: book

execute:
  freeze: auto

jupyter: 
  kernelspec: 
    name: hwan
    display_name: hwan
    language: python

book:
  title: "KAIST MFE, 2024 Spring"
  author: "Kim Hyeonghwan"
  date: "2024. 4. 29."
  cover-image: cover.png
  chapters:
    - index.qmd

    - part : Python('24봄)
      chapters: 
        - 1. Python Basics.ipynb
        - 2. Containers.ipynb
        - 3. Control Flows.ipynb
        - 4. Functions.ipynb
        - 5. Numpy.ipynb
        - 6. Pandas.ipynb
        - 7. Pandas_practice.ipynb
        - Python Quiz1.qmd
        - Python Quiz2.qmd
        - Python Quiz3.qmd
        - Python Quiz4.qmd
        - Python Quiz5.qmd
        - Python midterm_quarto.qmd
        - Python final.qmd
    - part : 채권분석&기간구조('24봄)
      chapters:
        - 채권분석_hw1.qmd
        - 채권분석_hw2.qmd
        - 채권분석_hw3.qmd
        - 이자율기간구조_hw1.qmd
        - 이자율기간구조_hw2.qmd
        - 이자율기간구조_hw3.qmd
    - part : 투자분석('24봄)
      chapters: 
        - investment_hw1.qmd
        - investment_hw2.qmd
        - investment_hw3.qmd
        - investment_hw4.qmd
    - part : 재무회계('24봄)
      chapters:
        - 재무회계_ch1-3.qmd
        - 재무회계_ch4.qmd
        - 재무회계_ch5.qmd
        - 재무회계_ch6.qmd
        - 재무회계_ch8.qmd
        - 재무회계_ch9.qmd
        - 재무회계_ch10.qmd
        - 재무회계_ch11.qmd
    - part : 경영통계분석('24봄)
      chapters:
        - 경영통계분석_hw1.qmd
        - 경영통계분석_hw2.qmd 
        - 경영통계분석_hw3.qmd
        - 경영통계분석_hw4.qmd
        - 경영통계분석_hw5.qmd
        - 경영통계분석_hw6.qmd
  downloads: pdf

code-block-bg: true
code-block-border-left: "#31BAE9"

format:
  html:
    theme: cosmo
    linestretch : 2
    code-tools: true
    code-overflow: scroll
    monofont: 'Source Code Pro'
  pdf:
    documentclass: scrreprt
    include-in-header: header.tex
    papersize: A4
    margin-bottom: 30mm
    margin-top: 30mm
    margin-left: 15mm
    margin-right: 15mm
    monofontoptions: 
      - Scale=0.8


