# 채권분석 과제1 {.unnumbered}

## 1. CB

***(Question)***

전환사채를 액면 F 만큼 매입할 때 전환가가 P라면, 전환주식수는 F/P 로 주어진다. 특정 전환사채를 액면 1억원 만큼 시장에서 매입하였다. 매입가는 1억 1천만원이다. 전환가격은 5만원으로 주어져 있다.

해당 주식의 시장가 가 6만원일 때 전환하여 매도하였다면 투자자의 수익률은무엇인가? % 로 쓰되, 소수점 둘째 자리까지만 쓰시오.

***(Answer)***  9.09%

$$전환주식수 = \frac{1억원}{5만원} = 2,000주$$
$$전환주식의 가치 = 2000\times 60,000원=1억\,2천만원$$
$$투자원금=1억1천만원, 수익률=\frac{1.2억}{1.1억}-1\approx 9.09\%$$

## 2. FRN

***(Question)***

정부가 2년 만기 변동금리채권을 발행한다고 가정하자. 기준금리는 만기 1년 현물 이자율 (spot rate 또는 1년 만기 무이표채 국채의 이자율) 이고, 해당 변동금리채권의 이자는 1년마다 계산하여 지급한다, 즉 1년 말에 지급하고 2년 만기시 원금과 함께 지급한다.

현재 1년 spot rate 을 $r_{1,0}$, 1년 후 spot rate 을 $r_{1,1}$ 이라 하면 받게 되는 총 금액은 액면 100 당 $100r_{1,0}$ (1년 시점) 과 $100(1 + r_{1,1})$ (2년 시점)이다. 물론 $r_{1,1}$ 은 현재 시점에서는 알 수 없는 확률변수이다.

액면이 100 인 위의 2년 만기 변동금리채권의 현재 시점의 공정한 가격을 구하시오. 투자자는 시장에서 1년 만기 무이표채 국채를 현재 시점이던 1년 후 시점이던 자유롭게 거래할 수 있다.

***(Answer)*** 100

상기 FRN은 1년 만기 무이표 국채의 이자율만큼의 쿠폰을 지급하고 있다. 이러한 액면 100인 FRN의 현금흐름은 현재 1년 만기 무이표국채에 $100r_{1,0}$만큼 투자하고, 1년 뒤 만기시점에 다시 1년 만기 무이표국채에 $100+r_{1,1}$투자함으로써 복제할 수 있다.

즉, 해당 FRN은 무위험이자율 만큼의 연수익률을 보장하는 채권으로서 쿠폰=할인율이므로 **공정가격은 100(par-value)**에 형성되어야 한다.

::: {.callout-note title="Foward rate를 이용한 풀이"}
$r_{1,1}$은 확률변수이므로, FRN의 2년뒤 현금흐름 $100(1+r_{1,1})$을 현재가치로 환산한다면 그 공정가치는 $\frac{100(1+E[r_{1,1}])}{(1+r_{2,0})^2}$으로 표현할 수 있다.

한편, 1년뒤 1년 spot-rate의 기댓값은 foward rate으로 볼 수 있고, 현재시점의 2년 spot-rate는 $(1+r_{1,0})(1+f_{1,1})$로 표현할 수 있다. 따라서, FRN의 공정가격은 다음과 같다.

$$FRN\; price=\frac{100r_{1.0}}{1+r_{1,0}}+\frac{100(1+E[r_{1,1}])}{1+r_{2,0}}=\frac{100r_{1.0}}{1+r_{1,0}}+\frac{100(1+f_{1,1})}{(1+r_{1,0})(1+f_{1,1})}=\frac{100(1+r_{1,0})}{1+r_{1,0}}=100$$
:::



## 3. YTM

***(Question)***

잔존만기가 3년이고 연 8% 이자를 6개월마다 제공하는 채권을 가정하자. A 투자자는 이 채권에 관심이 있고 거래하는 딜러는 100달러 액면당 92.5067 달러를 요구한다.

이때 이 채권의 수익률은 얼마인가? % 로 표시하되 소수점은 반올림하여 정수로 나타내시오.

***(Answer)*** 11%

채권의 수익률 $y$와 가격에 관한 산식은 다음과 같다.

$$92.5067=\sum_{k=1}^6\frac{8/2}{(1+y/2)^{k}}+\frac{100}{(1+y/2)^{6}}$$

이를 엑셀 해찾기 기능으로 근사한 $y$값은 약 11%이다.

## 4. Continuous compounding

***(Question)*** 10.71%

위의 문제는 compounding frequency 를 연 1회로 가정하고 있다. 이것은 이산복리법이다. 이 frequency가 무한이 되는 연속복리법에 따르면 1달러 투자가 1년 후에 $e^y$ 가 된다. 여기서 $y$ 는
연속복리이자율이다.

위 현금흐름 수익률을 연속복리이자율로 표현하시오. %로 나타내되 소수점 둘째 자리까지 쓰시오.

***(Answer)***

(3)의 현금흐름을 연속복리로 표현하면 다음과 같다.

$$92.5067=\sum_{k=1}^6\frac{8}{2}e^{-0.5ky}+100e^{-3y}$$

이를 엑셀 해찾기 기능으로 근사한 $y$값은 10.71%이다.

::: {.callout-note title="수익률 관계를 이용한 풀이"}
(3)의 수식과 비교하여 단순히 $e^{0.5y_{continuous}}=(1+y_{annual}/2)=1.055$로 표현할 수 있고 값은 10.71%로 오차범위 내에서 동일하다.
:::

## 5. Arbitrage

***(Question)***

아래와 같은 세 개의 채권이 시장에서 거래되고 있다. 트레이더 B 는 이를 보고 곧 차익거래의 기회가 있음을 파악하고 전략적으로 거래하여 이익을 얻었다. 어떤 전략이 가능할지 본인의 생각을
기술하시오.

- 채권 a: 만기 1년 무이표채, 액면 100 당 가격 90
- 채권 b: 만기 2년 무이표채, 액면 100 당 가격 80
- 채권 c: 만기 2년 이표채, coupon rate 10%, 매년 말 이자지급, 액면 100 당 가격 100

***(Answer)*** 채권a:채권b=1:11로 투자하여 채권c를 만들고 시장에 매도

채권a와 채권b의 수익률은 zero-rates이며, 이를 $y_a,y_b$라고 할 때, 다음과 같이 쓸 수 있다.
$$\frac{100}{1+y_a}=90,\; \frac{100}{(1+y_b)^2}=80 \Rightarrow \frac{1}{1+y_a}=0.9,\;\frac{1}{(1+y_b)^2}=0.8$$

이를 이용하여 채권c의 현금흐름을 평가하면, $\frac{10}{1+y_a}+\frac{110}{(1+y_b)^2}=9+88=97$

즉, **액면 100인 채권c의 공정가격은 97이나, 현재 100에 거래되고 있으므로 3만큼 고평가**되어있는 상태이다. 따라서 트레이더B가 **채권a:채권b=1:11 비중으로 매수한다면 액면이 10인 채권c의 현금흐름을 정확하게 복제**할 수 있는데, 이를 이용하면 무위험 차익거래를 할 수 있다.

예를 들어,

(1) 액면 100억원 채권c를 시장에 매도(공매도 or 발행)하여 100억원의 자금을 조달

(2) 액면 10억원 채권a를 9억원에, 액면 110억원 채권b를 88억원에 매수

(3) 1년뒤 채권a의 원금 10억을 받아 채권c의 이표 10억원을 값고, 2년뒤 채권b의 원금 110억을 받아 채권c의 원금+이표 110억원을 값을 수 있으므로 현재 시점에서 미래현금흐름은 0임(리스크=0)

(4) 한편, 현재 100억원을 빌려 97억원을 사용하였으므로 3억원의 무위험차익 실현 (또는, 남은 3억원을 채권b에 투자하여 현재시점의 투입자본없이 2년뒤 3.75억의 수익 실현 가능)